//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSBC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacione
    {
        public int CalificacionId { get; set; }
        public string Alumno { get; set; }
        public string Calificacion1 { get; set; }
        public string Calificacion2 { get; set; }
        public string Calificacion3 { get; set; }
        public string Promedio { get; set; }
    
        public virtual Alumno Alumno1 { get; set; }
    }
}
