//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSBC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        public string NumeroEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string HorasAsignadas { get; set; }
    }
}
